name: Sync Demo Branch

on:
  push:
    branches:
      - main

jobs:
  sync-demo-branch:
    runs-on: ubuntu-latest
    steps:
      # Checkout the demo branch first, this is where we'll merge into
      - name: Checkout demo branch
        uses: actions/checkout@v4
        with:
          ref: 'demo'
          token: ${{ secrets.DEMO_UPDATE_PAT }}
          fetch-depth: 0 # Needed for merge history

      # Verify .gitattributes
      - name: Verify .gitattributes
        run: |
          echo "Checking .gitattributes content:"
          cat .gitattributes || echo ".gitattributes not found!"

      # Configure Git user for the commit
      - name: Configure Git User
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions-bot@github.com"

      # Disable autocrlf
      - name: Disable autocrlf
        run: git config --global core.autocrlf false

      # Fetch the latest changes from the remote, including main
      - name: Fetch origin
        run: git fetch origin

      # Perform the merge from main into demo
      - name: Merge main into demo TEST without -X theirs
        run: |
          # TEST: Removed -X theirs to see if .gitattributes merge=ours works alone
          git merge --no-ff origin/main -m "Auto-merge main into demo (TEST: without -X theirs)"

      # Push the merge commit (and resolved changes) back to the demo branch
      - name: Push changes to demo
        run: |
          git push origin demo
